src/Entity/Log.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogRepository")
 */
class Log
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instruction_letter;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $driver;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Truck")
     * @ORM\JoinColumn(nullable=false)
     */
    private $truck;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $load_location;

    /**
     * @ORM\Column(type="time")
     */
    private $time_depart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInstructionLetter(): ?string
    {
        return $this->instruction_letter;
    }

    public function setInstructionLetter(?string $instruction_letter): self
    {
        $this->instruction_letter = $instruction_letter;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDriver(): ?user
    {
        return $this->driver;
    }

    public function setDriver(?user $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    public function getTruck(): ?truck
    {
        return $this->truck;
    }

    public function setTruck(?truck $truck): self
    {
        $this->truck = $truck;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getLoadLocation(): ?string
    {
        return $this->load_location;
    }

    public function setLoadLocation(string $load_location): self
    {
        $this->load_location = $load_location;

        return $this;
    }

    public function getTimeDepart(): ?\DateTimeInterface
    {
        return $this->time_depart;
    }

    public function setTimeDepart(\DateTimeInterface $time_depart): self
    {
        $this->time_depart = $time_depart;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getEvent(): ?string
    {
        return $this->event;
    }

    public function setEvent(string $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/LogType.php
<?php

namespace App\Form;

use App\Entity\Log;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('instruction_letter')
            ->add('date')
            ->add('amount')
            ->add('load_location')
            ->add('time_depart')
            ->add('location')
            ->add('event')
            ->add('driver')
            ->add('truck')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Log::class,
        ]);
    }
}

src/Form/LogsType.php
<?php

namespace App\Form;

use App\Entity\Logs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('intruction_letter')
            ->add('date')
            ->add('amount')
            ->add('load_location')
            ->add('time_depart')
            ->add('location')
            ->add('event')
            ->add('driver')
            ->add('truck')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logs::class,
        ]);
    }
}

src/Controller/LogController.php
<?php

namespace App\Controller;

use App\Entity\Log;
use App\Form\LogType;
use App\Repository\LogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/log")
 */
class LogController extends AbstractController
{
    private $security;
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="log_index", methods={"GET"})
     */
    public function index(LogRepository $logRepository): Response
    {
        $id = $this->getUser()->getId();
        if ($this->security->isGranted('ROLE_SUPER_ADMIN')) {
            return $this->render('log/index.html.twig', [
                'logs' => $logRepository->findAll(),
            ]);
        }
        elseif($this->security->isGranted('ROLE_USER')){
            return $this->render('log/index.html.twig', [
                'logs' => $logRepository->logFinder($id)
            ]);
        }else {
            return $this->redirectToRoute('noaccess');
        }
    }

    /**
     * @Route("/new", name="log_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $log = new Log();
        $form = $this->createForm(LogType::class, $log);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($log);
            $entityManager->flush();

            return $this->redirectToRoute('log_index');
        }

        return $this->render('log/new.html.twig', [
            'log' => $log,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="log_show", methods={"GET"})
     */
    public function show(Log $log): Response
    {
        return $this->render('log/show.html.twig', [
            'log' => $log,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="log_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Log $log): Response
    {
        $form = $this->createForm(LogType::class, $log);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('log_index', [
                'id' => $log->getId(),
            ]);
        }

        return $this->render('log/edit.html.twig', [
            'log' => $log,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="log_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Log $log): Response
    {
        if ($this->isCsrfTokenValid('delete'.$log->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($log);
            $entityManager->flush();
        }

        return $this->redirectToRoute('log_index');
    }
}

templates/log/_delete_form.html.twig
<form method="post" action="{{ path('log_delete', {'id': log.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ log.id) }}">
    <button class="btn">Delete</button>
</form>

templates/log/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/log/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Log{% endblock %}

{% block body %}
    <h1>Edit Log</h1>

    {{ include('log/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('log_index') }}">back to list</a>
    {{ include('log/_delete_form.html.twig') }}
{% endblock %}

templates/log/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log index{% endblock %}

{% block body %}
    <h1>Log index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Instruction_letter</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Load_location</th>
                <th>Time_depart</th>
                <th>Location</th>
                <th>Event</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for log in logs %}
            <tr>
                <td>{{ log.id }}</td>
                <td>{{ log.instructionLetter }}</td>
                <td>{{ log.date ? log.date|date('d-m-Y') : '' }}</td>
                <td>{{ log.amount }}</td>
                <td>{{ log.loadLocation }}</td>
                <td>{{ log.timeDepart ? log.timeDepart|date('H:i') : '' }}</td>
                <td>{{ log.location }}</td>
                <td>{{ log.event }}</td>
                <td>
                    <a href="{{ path('log_show', {'id': log.id}) }}">show</a>
                    <a href="{{ path('log_edit', {'id': log.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('log_new') }}">Create new</a>
    {% endif %}

{% endblock %}

templates/log/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Log{% endblock %}

{% block body %}
    <h1>Create new Log</h1>

    {{ include('log/_form.html.twig') }}

    <a href="{{ path('log_index') }}">back to list</a>
{% endblock %}

templates/log/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log{% endblock %}

{% block body %}
    <h1>Log</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ log.id }}</td>
            </tr>
            <tr>
                <th>Instruction_letter</th>
                <td>{{ log.instructionLetter }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ log.date ? log.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ log.amount }}</td>
            </tr>
            <tr>
                <th>Load_location</th>
                <td>{{ log.loadLocation }}</td>
            </tr>
            <tr>
                <th>Time_depart</th>
                <td>{{ log.timeDepart ? log.timeDepart|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ log.location }}</td>
            </tr>
            <tr>
                <th>Event</th>
                <td>{{ log.event }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('log_index') }}">back to list</a>

    <a href="{{ path('log_edit', {'id': log.id}) }}">edit</a>
    {% if is_granted('ROLE_ADMIN') %}
    {{ include('log/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}