src/Entity/Truck.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TruckRepository")
 */
class Truck
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $license_plate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $build_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLicensePlate(): ?string
    {
        return $this->license_plate;
    }

    public function setLicensePlate(string $license_plate): self
    {
        $this->license_plate = $license_plate;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getBuildDate(): ?string
    {
        return $this->build_date;
    }

    public function setBuildDate(?string $build_date): self
    {
        $this->build_date = $build_date;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getLicensePlate() . ' - ' .$this->getBrand();
    }
}

src/Form/TruckType.php
<?php

namespace App\Form;

use App\Entity\Truck;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TruckType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('license_plate')
            ->add('brand')
            ->add('build_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Truck::class,
        ]);
    }
}

src/Controller/TruckController.php
<?php

namespace App\Controller;

use App\Entity\Truck;
use App\Form\Truck1Type;
use App\Repository\TruckRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/truck")
 */
class TruckController extends AbstractController
{
    private $security;
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="truck_index", methods={"GET"})
     */
    public function index(TruckRepository $truckRepository): Response
    {

        if ($this->security->isGranted('ROLE_SUPER_ADMIN')) {
            return $this->render('truck/index.html.twig', [
                'trucks' => $truckRepository->findAll(),
            ]);
        } else {
            return $this->redirectToRoute('noaccess');
        }
    }


    /**
     * @Route("/new", name="truck_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $truck = new Truck();
        $form = $this->createForm(Truck1Type::class, $truck);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($truck);
            $entityManager->flush();

            return $this->redirectToRoute('truck_index');
        }

        return $this->render('truck/new.html.twig', [
            'truck' => $truck,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="truck_show", methods={"GET"})
     */
    public function show(Truck $truck): Response
    {
        return $this->render('truck/show.html.twig', [
            'truck' => $truck,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="truck_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Truck $truck): Response
    {
        $form = $this->createForm(Truck1Type::class, $truck);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('truck_index', [
                'id' => $truck->getId(),
            ]);
        }

        return $this->render('truck/edit.html.twig', [
            'truck' => $truck,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="truck_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Truck $truck): Response
    {
        if ($this->isCsrfTokenValid('delete'.$truck->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($truck);
            $entityManager->flush();
        }

        return $this->redirectToRoute('truck_index');
    }
}

templates/truck/_delete_form.html.twig
<form method="post" action="{{ path('truck_delete', {'id': truck.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ truck.id) }}">
    <button class="btn">Delete</button>
</form>

templates/truck/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/truck/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Truck{% endblock %}

{% block body %}
    <h1>Edit Truck</h1>

    {{ include('truck/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('truck_index') }}">back to list</a>

    {{ include('truck/_delete_form.html.twig') }}
{% endblock %}

templates/truck/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Truck index{% endblock %}

{% block body %}
    <h1>Truck index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>License_plate</th>
                <th>Brand</th>
                <th>Build_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for truck in trucks %}
            <tr>
                <td>{{ truck.id }}</td>
                <td>{{ truck.licensePlate }}</td>
                <td>{{ truck.brand }}</td>
                <td>{{ truck.buildDate }}</td>
                <td>
                    <a href="{{ path('truck_show', {'id': truck.id}) }}">show</a>
                    <a href="{{ path('truck_edit', {'id': truck.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('truck_new') }}">Create new</a>
{% endblock %}

templates/truck/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Truck{% endblock %}

{% block body %}
    <h1>Create new Truck</h1>

    {{ include('truck/_form.html.twig') }}

    <a href="{{ path('truck_index') }}">back to list</a>
{% endblock %}

templates/truck/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Truck{% endblock %}

{% block body %}
    <h1>Truck</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ truck.id }}</td>
            </tr>
            <tr>
                <th>License_plate</th>
                <td>{{ truck.licensePlate }}</td>
            </tr>
            <tr>
                <th>Brand</th>
                <td>{{ truck.brand }}</td>
            </tr>
            <tr>
                <th>Build_date</th>
                <td>{{ truck.buildDate }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('truck_index') }}">back to list</a>

    <a href="{{ path('truck_edit', {'id': truck.id}) }}">edit</a>

    {{ include('truck/_delete_form.html.twig') }}
{% endblock %}